### ISSUE TITLE
LengthUnit should extend float, not int

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/kittycad.py#203]
The [LengthUnit](https://github.com/KittyCAD/kittycad.py/blob/a1a02a1230b371962677b46ed6913043fe7113a6/kittycad/models/length_unit.py) only accepts int values and not floats. Non-integer inputs are rounded.

This prevents us from sketching arcs with non-integer radii, or extruding sketches to a non-integer depth.

This is a code generation error in the python lib only. In the typescript lib, [LengthUnit is a number](https://github.com/KittyCAD/kittycad.ts/blob/cd8b791b4950d986633c1cee73b3b04ac4a49f6b/src/models.ts#L1901). In the rust crate, we use f64.

**Comment by jessfraz** [comment]
done pushed 1 line change https://github.com/KittyCAD/kittycad.py/commit/532fbb352c1aeb896964b40077128f86ac2ae028#diff-5143dab0d2c336409b9b46ca57eff9a2bf4df5fc92a27c5aacdca66365e8971aL1034
